export default {
  "types": [{
      "type": "wenyuan",
      "title": "文苑",
      "src": "https://www.maocanhua.cn/images/essay_tag/wenyuan.jpg"
  },{
      "type": "qinggan",
      "title": "情感",
      "src": "https://www.maocanhua.cn/images/essay_tag/qinggan.jpg"
  }, {
      "type": "shehui",
      "title": "社会",
      "src": "https://www.maocanhua.cn/images/essay_tag/shehui.jpg"
  }, {
      "type": "shenghuo",
      "title": "生活",
      "src": "https://www.maocanhua.cn/images/essay_tag/shenghuo.jpg"
  }, {
      "type": "rensheng",
      "title": "人生",
      "src": "https://www.maocanhua.cn/images/essay_tag/rensheng.jpg"
  }, {
      "type": "renwu",
      "title": "人物",
      "src": "https://www.maocanhua.cn/images/essay_tag/renwu.jpg"
  }, {
      "type": "lizhi",
      "title": "励志",
      "src": "https://www.maocanhua.cn/images/essay_tag/lizhi.jpg"
  }, {
      "type": "shiye",
      "title": "视野",
      "src": "https://www.maocanhua.cn/images/essay_tag/shiye.jpg"
  }, {
      "type": "xinling",
      "title": "心灵",
      "src": "https://www.maocanhua.cn/images/essay_tag/xinling.jpg"
  }, {
      "type": "xiaoyuan",
      "title": "校园",
      "src": "https://www.maocanhua.cn/images/essay_tag/xiaoyuan.jpg"
  }, {
      "type": "zhichang",
      "title": "职场",
      "src": "https://www.maocanhua.cn/images/essay_tag/zhichang.jpg"
  }, {
      "type": "redu",
      "title": "热读",
      "src": "https://www.maocanhua.cn/images/essay_tag/redu.jpg"
  }]
}
